# Dependency Review Configuration
# This file configures the GitHub dependency review action
# Note: Only certain options are supported by actions/dependency-review-action@v4

# License configuration - use only allow-licenses (cannot combine with deny-licenses)
allow-licenses:
  - MIT
  - Apache-2.0
  - Apache-2.0 WITH LLVM-exception
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - Unicode-3.0
  - Unlicense
  - 0BSD
  - Zlib
  - CC0-1.0
  - MPL-2.0
  - BUSL-1.1  # Business Source License for SurrealDB
  - CDLA-Permissive-2.0  # Community Data License Agreement
  - OpenSSL  # OpenSSL License for aws-lc-sys

# Vulnerability configuration
vulnerability-check: true
license-check: false  # Disabled due to SPDX detection issues, using cargo-deny instead
fail-on-severity: moderate

# Comment configuration
comment-summary-in-pr: true

# Retry configuration for transient failures
retry-on-snapshot-warnings: true
