# Cargo Audit Configuration
# This file configures cargo-audit security vulnerability scanning
# Documentation: https://docs.rs/cargo-audit/latest/cargo_audit/

[advisories]
# Ignore specific security advisories
# Format: "RUSTSEC-YYYY-NNNN"
ignore = [
    # Unmaintained transitive dependencies that don't pose security risks
    "RUSTSEC-2024-0436",  # paste v1.0.15 (via rmp → surrealdb)
    #   Status: Monitoring - waiting for SurrealDB to migrate away from rmp
    #   Review: 2025-Q2 - reassess if still present
    #   Risk Assessment: Low - paste is only used for procedural macros, no runtime security impact
    #   Mitigation: Transitive dependency only, no direct usage in our codebase
]

# Severity levels to report
# Options: "low", "medium", "high", "critical"
severity-threshold = "low"

# Database configuration
[database]
# Automatically update the advisory database
auto-update = true

# Fetch timeout in seconds
fetch-timeout = 30

# Output configuration
[output]
# Output format: "json", "toml", "yaml"
format = "json"

# Show additional information
show-tree = false
