// This file is @generated by prost-build.
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AdminUserMessage {
    #[prost(string, tag = "1")]
    pub full_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub email: ::prost::alloc::string::String,
    /// password_hash is not included in the message for now
    #[prost(string, tag = "3")]
    pub profile_image: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub is_super_admin: bool,
    #[prost(string, tag = "5")]
    pub created_by: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub updated_by: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "7")]
    pub created_at: ::core::option::Option<::pbjson_types::Timestamp>,
    #[prost(message, optional, tag = "8")]
    pub updated_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
