//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "admin_users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub email: String,
    pub password: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub created_by: Option<String>,
    pub updated_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        super::admin_users_roles::Relation::Roles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::admin_users_roles::Relation::AdminUsers.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
