[package]
name = "leptop-admin"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = "0.1.7"
console_log = { version = "1.0.0", features = ["color"] }
leptos = { version = "0.8.5", features = ["csr"] }
log = "0.4.27"
