[build]
# Parallel compilation
jobs = 8
# Use sccache for distributed caching (only if available)
# rustc-wrapper = "sccache"  # Commented out to avoid CI failures when sccache is not available
# Additional optimization flags
rustflags = ["-C", "target-cpu=native"]

[profile.dev]
# Faster debug builds
debug = 1
opt-level = 0
incremental = true

[profile.dev-fast]
inherits = "dev"
opt-level = 1
debug = false
incremental = true
codegen-units = 256
