/**
 * @fileoverview gRPC-Web generated client stub for dashboard
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.32.0
// source: dashboard.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as dashboard_pb from './dashboard_pb'; // proto import: "dashboard.proto"


export class DashboardClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorDashboard = new grpcWeb.MethodDescriptor(
    '/dashboard.Dashboard/Dashboard',
    grpcWeb.MethodType.UNARY,
    dashboard_pb.DashboardRequest,
    dashboard_pb.DashboardResponse,
    (request: dashboard_pb.DashboardRequest) => {
      return request.serializeBinary();
    },
    dashboard_pb.DashboardResponse.deserializeBinary
  );

  dashboard(
    request: dashboard_pb.DashboardRequest,
    metadata?: grpcWeb.Metadata | null): Promise<dashboard_pb.DashboardResponse>;

  dashboard(
    request: dashboard_pb.DashboardRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: dashboard_pb.DashboardResponse) => void): grpcWeb.ClientReadableStream<dashboard_pb.DashboardResponse>;

  dashboard(
    request: dashboard_pb.DashboardRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: dashboard_pb.DashboardResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/dashboard.Dashboard/Dashboard',
        request,
        metadata || {},
        this.methodDescriptorDashboard,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/dashboard.Dashboard/Dashboard',
    request,
    metadata || {},
    this.methodDescriptorDashboard);
  }

}

