/**
 * @fileoverview gRPC-Web generated client stub for entity
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.32.0
// source: entity.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as entity_pb from './entity_pb'; // proto import: "entity.proto"


export class EnttyServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorPaginate = new grpcWeb.MethodDescriptor(
    '/entity.EnttyService/Paginate',
    grpcWeb.MethodType.UNARY,
    entity_pb.EntityPaginateRequest,
    entity_pb.EntityPaginateResponse,
    (request: entity_pb.EntityPaginateRequest) => {
      return request.serializeBinary();
    },
    entity_pb.EntityPaginateResponse.deserializeBinary
  );

  paginate(
    request: entity_pb.EntityPaginateRequest,
    metadata?: grpcWeb.Metadata | null): Promise<entity_pb.EntityPaginateResponse>;

  paginate(
    request: entity_pb.EntityPaginateRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: entity_pb.EntityPaginateResponse) => void): grpcWeb.ClientReadableStream<entity_pb.EntityPaginateResponse>;

  paginate(
    request: entity_pb.EntityPaginateRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: entity_pb.EntityPaginateResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/entity.EnttyService/Paginate',
        request,
        metadata || {},
        this.methodDescriptorPaginate,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/entity.EnttyService/Paginate',
    request,
    metadata || {},
    this.methodDescriptorPaginate);
  }

  methodDescriptorStoreEntity = new grpcWeb.MethodDescriptor(
    '/entity.EnttyService/StoreEntity',
    grpcWeb.MethodType.UNARY,
    entity_pb.StoreEntityRequest,
    entity_pb.StoreEntityResponse,
    (request: entity_pb.StoreEntityRequest) => {
      return request.serializeBinary();
    },
    entity_pb.StoreEntityResponse.deserializeBinary
  );

  storeEntity(
    request: entity_pb.StoreEntityRequest,
    metadata?: grpcWeb.Metadata | null): Promise<entity_pb.StoreEntityResponse>;

  storeEntity(
    request: entity_pb.StoreEntityRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: entity_pb.StoreEntityResponse) => void): grpcWeb.ClientReadableStream<entity_pb.StoreEntityResponse>;

  storeEntity(
    request: entity_pb.StoreEntityRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: entity_pb.StoreEntityResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/entity.EnttyService/StoreEntity',
        request,
        metadata || {},
        this.methodDescriptorStoreEntity,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/entity.EnttyService/StoreEntity',
    request,
    metadata || {},
    this.methodDescriptorStoreEntity);
  }

  methodDescriptorGetEntity = new grpcWeb.MethodDescriptor(
    '/entity.EnttyService/GetEntity',
    grpcWeb.MethodType.UNARY,
    entity_pb.GetEntityRequest,
    entity_pb.GetEntityResponse,
    (request: entity_pb.GetEntityRequest) => {
      return request.serializeBinary();
    },
    entity_pb.GetEntityResponse.deserializeBinary
  );

  getEntity(
    request: entity_pb.GetEntityRequest,
    metadata?: grpcWeb.Metadata | null): Promise<entity_pb.GetEntityResponse>;

  getEntity(
    request: entity_pb.GetEntityRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: entity_pb.GetEntityResponse) => void): grpcWeb.ClientReadableStream<entity_pb.GetEntityResponse>;

  getEntity(
    request: entity_pb.GetEntityRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: entity_pb.GetEntityResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/entity.EnttyService/GetEntity',
        request,
        metadata || {},
        this.methodDescriptorGetEntity,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/entity.EnttyService/GetEntity',
    request,
    metadata || {},
    this.methodDescriptorGetEntity);
  }

  methodDescriptorUpdateEntity = new grpcWeb.MethodDescriptor(
    '/entity.EnttyService/UpdateEntity',
    grpcWeb.MethodType.UNARY,
    entity_pb.UpdateEntityRequest,
    entity_pb.UpdateEntityResponse,
    (request: entity_pb.UpdateEntityRequest) => {
      return request.serializeBinary();
    },
    entity_pb.UpdateEntityResponse.deserializeBinary
  );

  updateEntity(
    request: entity_pb.UpdateEntityRequest,
    metadata?: grpcWeb.Metadata | null): Promise<entity_pb.UpdateEntityResponse>;

  updateEntity(
    request: entity_pb.UpdateEntityRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: entity_pb.UpdateEntityResponse) => void): grpcWeb.ClientReadableStream<entity_pb.UpdateEntityResponse>;

  updateEntity(
    request: entity_pb.UpdateEntityRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: entity_pb.UpdateEntityResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/entity.EnttyService/UpdateEntity',
        request,
        metadata || {},
        this.methodDescriptorUpdateEntity,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/entity.EnttyService/UpdateEntity',
    request,
    metadata || {},
    this.methodDescriptorUpdateEntity);
  }

  methodDescriptorPutEntityIdentifier = new grpcWeb.MethodDescriptor(
    '/entity.EnttyService/PutEntityIdentifier',
    grpcWeb.MethodType.UNARY,
    entity_pb.PutEntityIdentifierRequest,
    entity_pb.PutEntityIdentifierResponse,
    (request: entity_pb.PutEntityIdentifierRequest) => {
      return request.serializeBinary();
    },
    entity_pb.PutEntityIdentifierResponse.deserializeBinary
  );

  putEntityIdentifier(
    request: entity_pb.PutEntityIdentifierRequest,
    metadata?: grpcWeb.Metadata | null): Promise<entity_pb.PutEntityIdentifierResponse>;

  putEntityIdentifier(
    request: entity_pb.PutEntityIdentifierRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: entity_pb.PutEntityIdentifierResponse) => void): grpcWeb.ClientReadableStream<entity_pb.PutEntityIdentifierResponse>;

  putEntityIdentifier(
    request: entity_pb.PutEntityIdentifierRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: entity_pb.PutEntityIdentifierResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/entity.EnttyService/PutEntityIdentifier',
        request,
        metadata || {},
        this.methodDescriptorPutEntityIdentifier,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/entity.EnttyService/PutEntityIdentifier',
    request,
    metadata || {},
    this.methodDescriptorPutEntityIdentifier);
  }

  methodDescriptorDeleteEntity = new grpcWeb.MethodDescriptor(
    '/entity.EnttyService/DeleteEntity',
    grpcWeb.MethodType.UNARY,
    entity_pb.DeleteEntityRequest,
    entity_pb.DeleteEntityResponse,
    (request: entity_pb.DeleteEntityRequest) => {
      return request.serializeBinary();
    },
    entity_pb.DeleteEntityResponse.deserializeBinary
  );

  deleteEntity(
    request: entity_pb.DeleteEntityRequest,
    metadata?: grpcWeb.Metadata | null): Promise<entity_pb.DeleteEntityResponse>;

  deleteEntity(
    request: entity_pb.DeleteEntityRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: entity_pb.DeleteEntityResponse) => void): grpcWeb.ClientReadableStream<entity_pb.DeleteEntityResponse>;

  deleteEntity(
    request: entity_pb.DeleteEntityRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: entity_pb.DeleteEntityResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/entity.EnttyService/DeleteEntity',
        request,
        metadata || {},
        this.methodDescriptorDeleteEntity,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/entity.EnttyService/DeleteEntity',
    request,
    metadata || {},
    this.methodDescriptorDeleteEntity);
  }

}

