name: React Admin deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
          run:
            working-directory: 'ts-grpc-vite-admin'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

#    - name: Copy files via ssh
#      uses: appleboy/scp-action@master
#      with:
#        host: ${{ secrets.HOST }}
#        username: ${{ secrets.USERNAME }}
#        key: ${{ secrets.SSH_KEY }}
#        source: "./ts-grpc-react-admin/build"
#        target: ${{ secrets.REACT_TARGET_PATH }}

    - name: deploy demo app
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "./ts-grpc-vite-admin/build"
        target: ${{ secrets.REACT_DEMO_TARGET_PATH }}
        timeout: 60s
        command_timeout: 10m
        overwrite: true
      continue-on-error: false
