name: Frontend deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
          run:
            working-directory: 'ts-grpc-vite-front'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build
    - name: Deploy demo front files via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "./ts-grpc-vite-front/dist"
        target: ${{ secrets.REACT_DEMO_TARGET_PATH }}
        strip_components: 1 
